apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhsi
resources:
  - 00-namespace-rhsi.yaml
  - 10-site.yaml
  - 20-postgres-standby-secret.yaml
  - 30-postgres-standby-deployment.yaml
  - 40-postgres-standby-service.yaml
  - 50-listener-postgres.yaml
  - 60-skupper-local-ca-configmap-job.yaml
