apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhsi-standby
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        # Provided by the ACM + GitOps integration
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: rhsi-standby
        requeueAfterSeconds: 60
  template:
    metadata:
      name: rhsi-standby-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/waynedovey/rhsi-edb-vault.git
        targetRevision: main
        path: rhsi/standby
      destination:
        namespace: rhsi
        # Filled automatically from ACM placement decisions
        server: "{{server}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
