apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhsi-operator
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: rhsi-operator
        requeueAfterSeconds: 60
  template:
    metadata:
      name: rhsi-operator-{{name}}
      labels:
        app.kubernetes.io/part-of: rhsi
    spec:
      project: default
      source:
        repoURL: https://github.com/waynedovey/rhsi-edb-vault.git
        targetRevision: main
        path: rhsi-operator
      destination:
        namespace: openshift-operators
        server: "{{server}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          # Namespace openshift-operators should already exist; keep this false.
          - CreateNamespace=false
