apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhsi-skupper-operator
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: all-openshift-clusters
      requeueAfterSeconds: 60
  template:
    metadata:
      name: rhsi-skupper-operator-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/waynedovey/rhsi-edb-vault.git
        targetRevision: main
        path: rhsi/operator
      destination:
        namespace: skupper-operator
        server: "{{server}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
