apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhsi-skupper-operator
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: rhsi-sites
        requeueAfterSeconds: 30
  template:
    metadata:
      name: rhsi-skupper-operator-{{name}}
      labels:
        app.kubernetes.io/part-of: rhsi
    spec:
      project: default
      source:
        repoURL: https://github.com/WayneDovey/rhsi-edb-vault.git
        targetRevision: HEAD
        path: skupper-operator
      destination:
        server: '{{server}}'
        namespace: rhsi
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
