apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhsi-operator
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: rhsi-operator
        requeueAfterSeconds: 60
  template:
    metadata:
      name: "rhsi-operator-{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/waynedovey/rhsi-edb-vault.git
        targetRevision: main
        path: rhsi/operator
      destination:
        server: "{{server}}"
        namespace: openshift-operators
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
