apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhsi-external-secrets-operator
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: rhsi-external-secrets-operator
      requeueAfterSeconds: 30
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: rhsi
      name: rhsi-external-secrets-operator-{{name}}
    spec:
      destination:
        namespace: external-secrets-operator
        server: '{{server}}'
      project: default
      source:
        path: external-secrets-operator
        repoURL: https://github.com/waynedovey/rhsi-edb-vault.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
