apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhsi-network-observer
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: rhsi-network-observer
        requeueAfterSeconds: 30
  template:
    metadata:
      name: rhsi-network-observer-{{name}}
      labels:
        app.kubernetes.io/part-of: rhsi
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: rhsi
      source:
        repoURL: https://github.com/waynedovey/rhsi-edb-vault.git
        targetRevision: main
        path: rhsi/network-observer
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
